name: reproduction-database

services:
  db:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 20
